### ISSUE TITLE
Update for Polymer 2.0

### ISSUE THREAD

**Issue by Splaktar** [webcomponents/angular-interop#3]
It's still early on (Alpha) but there are some breaking changes coming in Polymer 2.0 that will require updates to this example.

**Comment by rjcorwin** [comment]
Polymer 2 released! https://www.polymer-project.org/blog/2017-05-15-time-for-two.html

I just watched the announcement and demo from the Google IO 2017 videos (https://www.youtube.com/watch?v=assSM3rlvZ8&list=PLNYkxOF6rcICniLJ2rfj0FexlA-9zmJJE&index=7), am working on an Angular project (v4), and am excited about the potential of building Components for my Angular projects that that can be used in other projects like our legacy Backbone.js codebase.

**Comment by manekinekko** [comment]
fixed in #5

**Comment by rjcorwin** [comment]
Interesting stuff @manekinekko! Would love to see a walkthrough video on this explaining this https://github.com/webcomponents/angular-interop/blob/master/angular-cli/src/app/app.component.ts#L21
