### ISSUE TITLE
Fast and small by default

### ISSUE THREAD

**Issue by Splaktar** [webcomponents/angular-interop#4]
This repo should show users how to tie in Vulcanize and Angular's AOT compiler in order to generate the smallest/fastest possible application. 

These two tool chains aren't really designed to work together, so a clear example here would help everyone who is working on angular-polymer interop.

**Comment by rjcorwin** [comment]
Problem solved if this example would be refactored to be based on Angular CLI 1.0 generators. https://cli.angular.io/

**Comment by manekinekko** [comment]
fixed in #5
